package TestExceptionHandling;

import TestOopsAbstraction.TestDevDept;

public class TestException1 {
static TestDevDept dept;
 
public static void main(String[] args) {
	try {System.out.println(10/0);
		
	} catch (Exception e) {
		
	}
}
 


}
